version: '3.8'

services:
  bot:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - PAGE_ACCESS_TOKEN=${PAGE_ACCESS_TOKEN}
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    volumes:
      - ./logs:/app/logs